# High level control
planner_patience: 3.5
controller_patience: 6.5
clearing_rotation_allowed: true
conservative_reset_dist: 3

TrajectoryPlannerROS:
# Robot Configuration Parameters
  max_vel_x: 0.22
  min_vel_x: -0.22
  escape_vel: -0.22
  
  max_vel_y: 0.12
  min_vel_y: -0.12

  max_vel_theta:  0.5
  min_vel_theta: -0.5
  min_in_place_vel_theta: 0.3

  acc_lim_x: 1.0
  acc_lim_y: 1.0
  acc_lim_theta: 1.0

# Goal Tolerance Parameters
  xy_goal_tolerance: 0.15
  yaw_goal_tolerance: 0.15

  holonomic_robot: true

# Forward Simulation Parameters
  sim_time: 3.0
  sim_granularity: 0.025
  vx_samples: 6
  vy_samples: 6
  vtheta_samples: 12

# Trajectory Scoring Parameters
  goal_distance_bias: 0.8
  path_distance_bias: 0.6
  occdist_scale: 0.01
  heading_lookahead: 0.325
  dwa: true
  prefer_forward_cost_function: 0.4

  publish_cost_grid_pc: false

  oscillation_reset_dist: 0.08
  meter_scoring: true
  
NavfnROS:
    allow_unknown: true
    visualize_potential: true
