global_frame: map
robot_base_frame: base_link
static_map: false
update_frequency: 1
publish_frequency: 1
plugins:
   - {name: static_layer, type: "rtabmap_ros::StaticLayer"}
   - {name: obstacle_layer,   type: "costmap_2d::ObstacleLayer"}
   - {name: inflation_layer,  type: "costmap_2d::InflationLayer"}
